development:
  adapter: postgresql
  database: sexysix_development
  pool: 5
  timeout: 5000
  username: bsprague
test:
  adapter: postgresql
  database: sexysix_development
  pool: 5
  timeout: 5000
  username: bsprague
production:
  adapter: postgresql
  database: sexysix_development
  pool: 5
  timeout: 5000
  username: bsprague

